name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - run: bun install
      - run: |
          bun run test \
            --test-reporter spec \
            --test-reporter-destination stdout \
            --test-reporter lcov \
            --test-reporter-destination coverage/lcov.info

      - uses: actions/upload-artifact@v7
        with:
          file: coverage/lcov.info
          name: lcov.info

      - uses: barecheck/code-coverage-action@v1
        with:
          lcov-file: coverage/lcov.info

  pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - run: bun install
      - run: |
          bun run test \
            --test-reporter spec \
            --test-reporter-destination stdout \
            --test-reporter lcov \
            --test-reporter-destination coverage/lcov.info

      - uses: actions/download-artifact@v8
        with:
          name: lcov.info

      - uses: barecheck/code-coverage-action@v1
        with:
          lcov-file: coverage/lcov.info
          base-lcov-file: lcov.info
